" ---------------
" General Options
" ---------------

set nocompatible

set laststatus=2
set showmode
set showtabline=2

set encoding=utf-8
set number
set relativenumber
set scrolloff=3
set showcmd
set showmatch
set ttyfast

set viminfo=""

set wildmenu
set wildmode=list:longest

" Translate all tabs and indents to 4 spaces
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Configure command to show/hide invisible characters
nmap <silent> <leader>l :set list!<CR>
set listchars=tab:▸\ ,eol:¬

" Prevent accidental help menu invocations
map <F1> <nop>

" ---------------------
" Plugins with vim-plug
" ---------------------

" Automatically install the plugin manager if it is absent
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/morhetz/gruvbox.git'
call plug#end()

" -------------
" Colour Scheme
" -------------

set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum
set termguicolors

colorscheme gruvbox
set background=dark
